### ISSUE TITLE
Python 3.8 will break this extension

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Python-Extension#14]
The warning given when running Python 3.7 setup indicates that Python 3.8 won't work the extension:

```
.../py/pyext.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
```

**Comment by quaquel** [comment]
fix should be easy, but differs between python 3 and python2.

For python 3.3. and later, you should use

```python
from collections.abc import Mapping
```

for versions before 3.3, the current code is fine. So, you need to check the python version.

The fix is probably the following:

```python
import sys

if sys.version_info[0] >2 and sys.version_info[1] > 3:
    from collections.abc import Mapping
else:
    from collections import Mapping
```

**Comment by LaCuneta** [comment]
@quaquel Thanks for the suggestion, it works great!  Fixed [here](https://github.com/NetLogo/Python-Extension/commit/cc67f1a503a10a1d2673437e93e2263e5a888321).
