### ISSUE TITLE
[NetLogo version] Can't open traffic RL example with NetLogo 6.2.1

### ISSUE THREAD

**Issue by smarianimore** [NetLogo/Python-Extension#22]
Hi everybody,
as per title, demo file [Traffic Basic - Reinforcement.nlogo](https://github.com/NetLogo/Python-Extension/blob/master/demos/Traffic%20Basic%20-%20Reinforcement.nlogo) won't open in NetLogo 6.2.1.
No meaningful error message is shown, just a generic can't load model.

Is there a required version to open such a demo?

**Comment by LaCuneta** [comment]
@smarianimore Sorry for the much delayed reply.  That model was written in NetLogo 6.0.2, but it should work in any version of NetLogo of that version or later.  I just tested it in NetLogo 6.2.2 and it worked for me.  How were you loading the model?  Did you clone the repository first, or did you just download it?

**Comment by smarianimore** [comment]
Hi @LaCuneta , don't worry.
I just opened it via "File > open".
I just downloaded the example file, not cloned the repo.

As a side note, I eventually opened the file with a text editor and removed every line below the last comment line indicating the netlogo version: that way, the model opened and seems to work just fine.

Still no idea what the issue was though...

**Comment by LaCuneta** [comment]
Thanks for the extra information!  I'm not exactly sure what is going on there, then, but I'm glad you got it working.  I went ahead and bumped the models to 6.2.2, in case that helps for some reason.
