### ISSUE TITLE
sbt versions, git tags and GitHub Releases are out of sync.

### ISSUE THREAD

**Issue by EwoutH** [NetLogo/Python-Extension#25]
The version numbers for this project are out of sync:

- The latest sbt version is [0.5.3](https://github.com/NetLogo/Python-Extension/commit/a66a4da3a1382acd759a5ead9f206951493f71d4#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91).
- The latest git tag is [0.5.0](https://github.com/NetLogo/Python-Extension/releases/tag/0.5.0).
- The latest GitHub release is [0.4.1](https://github.com/NetLogo/Python-Extension/releases/tag/0.4.1).

This is confusing and can potentially introduce issues when cloning (what you think is) the latest version from git.

**Comment by LaCuneta** [comment]
Okay got the tags up to date.  We don't typically use the Releases feature on GitHub for extensions anymore, since we have the extensions manager to publish those packages, so I just removed the old ones to avoid the confusion.

**Comment by EwoutH** [comment]
Perfect, thanks!
