### ISSUE TITLE
Extension not respecting specified python 3 path

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Python-Extension#28]
![image](https://github.com/NetLogo/Python-Extension/assets/28215/2b64e6be-f326-48c6-a972-2dfe794b2d6c)

I specified a python path in the extension config menu, by `py:python3` still returns default python on my path. The properties file has the path I specified in it:

```
❯ cat "/home/bryan/.netlogo/6.3/py/py.properties"
#
#Sun May 28 10:47:32 PDT 2023
python2=
runtimePath=/home/bryan/mambaforge/envs/py11/bin/python
```

When I manually specify that python path, everything works as expected:

```
observer> py:setup "/home/bryan/mambaforge/envs/py11/bin/python"
observer> py:run "import sys"
observer> show py:runresult "sys.version"
observer: "3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]"
```

**Comment by LaCuneta** [comment]
This is [fixed here](https://github.com/NetLogo/Language-Library/commit/d625b622f642cb714415ed1d7733418c3cfe84d4) and a new 0.5.4 release of the Python extension to the extensions manager just went up so you should be able to test it out.
