### ISSUE TITLE
Have you ever had the good idea to put a compiled .jar in the release or package? Obviously not

### ISSUE THREAD

**Issue by MahefaAbel** [NetLogo/Python-Extension#29]
JUST like other NetLogo extension !

No, you want that ALL users (who want use the f*cking py.jar) must install a tools 1Go+ for compile to get the small `py.jar` wanted.

UX = Zero

Sorry (not really !) to be obliged make this "Issue" but It make me angry to see that you have decided to not provide the f\*cking `py.jar` wanted ! (I don't ask the moon or the sun, just the small f\*cking `py.jar` ! Without installing Scala + Sbt + what the f*ck with it => 1Go+ !)

**Comment by MahefaAbel** [comment]
$ sbt package
[info] welcome to sbt 1.3.13 (Ubuntu Java 11.0.19)
[info] loading settings for project py-build from plugins.sbt ...
[info] loading project definition from /media/mahefa/Data/Soft/NetLogo-6.0.4-64/app/extensions/py/project
[info] loading settings for project py from build.sbt ...
[info] set current project to py (in build file:/media/mahefa/Data/Soft/NetLogo-6.0.4-64/app/extensions/py/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.jogamp.jogl:jogl-all:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /home/mahefa/.ivy2/local/org.jogamp.jogl/jogl-all/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/jogamp/jogl/jogl-all/2.4.0/jogl-all-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/netlogo/maven/org/jogamp/jogl/jogl-all/2.4.0/jogl-all-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/language-library/maven/org/jogamp/jogl/jogl-all/2.4.0/jogl-all-2.4.0.pom
[error]   jogl-all.jar not found under https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20210111/jar/
[error] Error downloading org.jogamp.gluegen:gluegen-rt:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /home/mahefa/.ivy2/local/org.jogamp.gluegen/gluegen-rt/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/jogamp/gluegen/gluegen-rt/2.4.0/gluegen-rt-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/netlogo/maven/org/jogamp/gluegen/gluegen-rt/2.4.0/gluegen-rt-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/language-library/maven/org/jogamp/gluegen/gluegen-rt/2.4.0/gluegen-rt-2.4.0.pom
[error]   gluegen-rt.jar not found under https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20210111/jar/
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.jogamp.jogl:jogl-all:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /home/mahefa/.ivy2/local/org.jogamp.jogl/jogl-all/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/jogamp/jogl/jogl-all/2.4.0/jogl-all-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/netlogo/maven/org/jogamp/jogl/jogl-all/2.4.0/jogl-all-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/language-library/maven/org/jogamp/jogl/jogl-all/2.4.0/jogl-all-2.4.0.pom
[error]   jogl-all.jar not found under https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20210111/jar/
[error] Error downloading org.jogamp.gluegen:gluegen-rt:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /home/mahefa/.ivy2/local/org.jogamp.gluegen/gluegen-rt/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/jogamp/gluegen/gluegen-rt/2.4.0/gluegen-rt-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/netlogo/maven/org/jogamp/gluegen/gluegen-rt/2.4.0/gluegen-rt-2.4.0.pom
[error]   not found: https://dl.cloudsmith.io/public/netlogo/language-library/maven/org/jogamp/gluegen/gluegen-rt/2.4.0/gluegen-rt-2.4.0.pom
[error]   gluegen-rt.jar not found under https://jogamp.org/deployment/archive/rc/v2.4.0-rc-20210111/jar/
[error] Total time: 14 s, completed Jun 19, 2023, 9:08:04 PM

**Comment by MahefaAbel** [comment]
![image](https://github.com/NetLogo/Python-Extension/assets/21125831/95bbb40f-c439-474e-9733-ff70dc261408)

![image](https://github.com/NetLogo/Python-Extension/assets/21125831/c8e33681-f3c6-4b4e-846f-cfa207ed0119)

If there are a `py.jar`, I and other do not have to deal with that error (quasi) insolvable.

**Comment by LaCuneta** [comment]
Your assumption that we do not distribute the `py.jar` file is incorrect.  The `py.jar` file comes bundled with [the NetLogo releases since 6.1.0](https://ccl.northwestern.edu/netlogo/download.shtml).  It is also available using [the extensions manager](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html) from within the NetLogo app, or as a direct download through [the NetLogo-Libraries repository](https://github.com/NetLogo/NetLogo-Libraries/blob/6.1/extensions/py-0.5.4.zip).   

For the most part, downloading the Python extension separately from the NetLogo app should not be necessary.  If you can clarify why you're trying to get it as a download I or others might be able to advise you on the best way.

It sounds like you are very frustrated and upset, but your messages appear intentionally rude to me.  I recommend trying to be more civil if you want further assistance.
